
spring:
  application:
    name: kafka-wrapper-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: all
      retries: 3
    consumer:
      group-id: default-wrapper-group
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  data:
    redis:
      host: localhost
      port: 6379

grpc:
  server:
    port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8087